/* ================================================================
   VOCAB-RU.JS — Rusça kelime verisi
   Bu dosya vocab-core.js YÜKLENDİKTEN SONRA çağrılmalıdır.
   Kolaydan zora: Alfabe -> A1 -> A2 -> B1 -> B2
================================================================ */

add("ru","A1","Alfabe","А а","A harfi (a sesi)","harf","Арбуз — это фрукт.","Karpuz bir meyvedir.");
add("ru","A1","Alfabe","Б б","Be harfi (b sesi)","harf","Барабан громкий.","Davul gürültülüdür.");
add("ru","A1","Alfabe","В в","Ve harfi (v sesi)","harf","Ветер сильный.","Rüzgar güçlü.");
add("ru","A1","Alfabe","Г г","Ge harfi (g sesi)","harf","Голубь летает.","Güvercin uçuyor.");
add("ru","A1","Alfabe","Д д","De harfi (d sesi)","harf","Дом новый.","Ev yeni.");
add("ru","A1","Alfabe","Е е","Ye harfi (ye sesi)","harf","Еда вкусная.","Yemek lezzetli.");
add("ru","A1","Alfabe","Ё ё","Yo harfi (yo sesi)","harf","Ёлка зелёная.","Çam ağacı yeşil.");
add("ru","A1","Alfabe","Ж ж","Je harfi (j sesi)","harf","Жираф высокий.","Zürafa uzundur.");
add("ru","A1","Alfabe","З з","Ze harfi (z sesi)","harf","Зима холодная.","Kış soğuktur.");
add("ru","A1","Alfabe","И и","İ harfi (i sesi)","harf","Игра интересная.","Oyun ilginç.");
add("ru","A1","Alfabe","Й й","Kısa İ harfi","harf","Мой дом здесь.","Evim burada.");
add("ru","A1","Alfabe","К к","Ka harfi (k sesi)","harf","Кот спит.","Kedi uyuyor.");
add("ru","A1","Alfabe","Л л","El harfi (l sesi)","harf","Лето тёплое.","Yaz sıcaktır.");
add("ru","A1","Alfabe","М м","Em harfi (m sesi)","harf","Мама дома.","Anne evde.");
add("ru","A1","Alfabe","Н н","En harfi (n sesi)","harf","Нитка тонкая.","İplik incedir.");
add("ru","A1","Alfabe","О о","O harfi (o sesi)","harf","Окно открыто.","Pencere açık.");
add("ru","A1","Alfabe","П п","Pe harfi (p sesi)","harf","Пример простой.","Örnek basit.");
add("ru","A1","Alfabe","Р р","Er harfi (r sesi)","harf","Рука болит.","El ağrıyor.");
add("ru","A1","Alfabe","С с","Es harfi (s sesi)","harf","Сумка новая.","Çanta yeni.");
add("ru","A1","Alfabe","Т т","Te harfi (t sesi)","harf","Тарелка круглая.","Tabak yuvarlaktır.");
add("ru","A1","Alfabe","У у","U harfi (u sesi)","harf","Ужин вкусный.","Akşam yemeği lezzetli.");
add("ru","A1","Alfabe","Ф ф","Ef harfi (f sesi)","harf","Фрукты полезны.","Meyveler faydalıdır.");
add("ru","A1","Alfabe","Х х","Ha harfi (h sesi)","harf","Хороший день.","İyi bir gün.");
add("ru","A1","Alfabe","Ц ц","Tse harfi (ts sesi)","harf","Цветок красивый.","Çiçek güzel.");
add("ru","A1","Alfabe","Ч ч","Çe harfi (ç sesi)","harf","Час прошёл.","Bir saat geçti.");
add("ru","A1","Alfabe","Ш ш","Şa harfi (ş sesi)","harf","Шар круглый.","Top yuvarlaktır.");
add("ru","A1","Alfabe","Щ щ","Şça harfi (uzun ş sesi)","harf","Щенок маленький.","Yavru köpek küçük.");
add("ru","A1","Alfabe","Ъ","Sert işaret (sessiz)","harf","Объект интересный.","Nesne ilginç.");
add("ru","A1","Alfabe","Ы","Kalın I harfi","harf","Мы дома.","Biz evdeyiz.");
add("ru","A1","Alfabe","Ь","Yumuşak işaret (sessiz)","harf","Дверь закрыта.","Kapı kapalı.");
add("ru","A1","Alfabe","Э э","E harfi (e sesi)","harf","Этаж высокий.","Kat yüksek.");
add("ru","A1","Alfabe","Ю ю","Yu harfi (yu sesi)","harf","Юг тёплый.","Güney sıcaktır.");
add("ru","A1","Alfabe","Я я","Ya harfi (ya sesi)","harf","Ягода сладкая.","Meyve tatlı.");
add("ru","A1","Selamlaşma","Привет","merhaba (samimi)","ifade","Привет, давно не виделись!","Merhaba, uzun zamandır görüşmedik!");
add("ru","A1","Selamlaşma","Здравствуйте","merhaba (resmi)","ifade","Здравствуйте, рад вас видеть.","Merhaba, sizi gördüğüme sevindim.");
add("ru","A1","Selamlaşma","Доброе утро","günaydın","ifade","Доброе утро, как ты спал?","Günaydın, nasıl uyudun?");
add("ru","A1","Selamlaşma","Добрый день","tünaydın","ifade","Добрый день всем.","Herkese tünaydın.");
add("ru","A1","Selamlaşma","Добрый вечер","iyi akşamlar","ifade","Добрый вечер, как прошёл день?","İyi akşamlar, gün nasıl geçti?");
add("ru","A1","Selamlaşma","Спокойной ночи","iyi geceler","ifade","Спокойной ночи, спи хорошо.","İyi geceler, iyi uykular.");
add("ru","A1","Selamlaşma","До свидания","hoşça kalın","ifade","До свидания, увидимся завтра.","Hoşça kalın, yarın görüşürüz.");
add("ru","A1","Selamlaşma","Пока","hoşça kal (samimi)","ifade","Пока, до встречи!","Hoşça kal, görüşürüz!");
add("ru","A1","Selamlaşma","Как дела?","nasılsın?","ifade","Привет, как дела?","Merhaba, nasılsın?");
add("ru","A1","Selamlaşma","Хорошо, спасибо","iyiyim, teşekkürler","ifade","Хорошо, спасибо, а ты?","İyiyim, teşekkürler, ya sen?");
add("ru","A1","Selamlaşma","Спасибо","teşekkürler","ifade","Спасибо большое!","Çok teşekkürler!");
add("ru","A1","Selamlaşma","Пожалуйста","rica ederim / lütfen","ifade","Пожалуйста, помоги мне.","Lütfen bana yardım et.");
add("ru","A1","Selamlaşma","Извините","affedersiniz","ifade","Извините, где вокзал?","Affedersiniz, tren istasyonu nerede?");
add("ru","A1","Selamlaşma","Простите","özür dilerim","ifade","Простите за опоздание.","Geciktiğim için özür dilerim.");
add("ru","A1","Selamlaşma","Да","evet","ifade","Да, конечно.","Evet, tabii ki.");
add("ru","A1","Selamlaşma","Нет","hayır","ifade","Нет, спасибо.","Hayır, teşekkürler.");
add("ru","A1","Selamlaşma","Меня зовут","benim adım","ifade","Меня зовут Анна.","Benim adım Anna.");
add("ru","A1","Selamlaşma","Как тебя зовут?","senin adın ne?","ifade","Как тебя зовут?","Senin adın ne?");
add("ru","A1","Selamlaşma","Приятно познакомиться","tanıştığımıza memnun oldum","ifade","Приятно познакомиться с вами.","Sizinle tanıştığımıza memnun oldum.");
add("ru","A1","Selamlaşma","Откуда ты?","nerelisin?","ifade","Откуда ты?","Nerelisin?");
add("ru","A1","Sayılar","один","bir (1)","sayı","У меня один брат.","Bir erkek kardeşim var.");
add("ru","A1","Sayılar","два","iki (2)","sayı","У меня два кота.","İki kedim var.");
add("ru","A1","Sayılar","три","üç (3)","sayı","Три яблока на столе.","Masada üç elma var.");
add("ru","A1","Sayılar","четыре","dört (4)","sayı","Четыре стула в комнате.","Odada dört sandalye var.");
add("ru","A1","Sayılar","пять","beş (5)","sayı","У меня пять пальцев.","Beş parmağım var.");
add("ru","A1","Sayılar","шесть","altı (6)","sayı","Шесть часов вечера.","Akşam saat altı.");
add("ru","A1","Sayılar","семь","yedi (7)","sayı","Семь дней в неделе.","Haftada yedi gün var.");
add("ru","A1","Sayılar","восемь","sekiz (8)","sayı","Восемь книг на полке.","Rafta sekiz kitap var.");
add("ru","A1","Sayılar","девять","dokuz (9)","sayı","Девять часов утра.","Sabah saat dokuz.");
add("ru","A1","Sayılar","десять","on (10)","sayı","У меня десять пальцев на ногах.","On ayak parmağım var.");
add("ru","A1","Sayılar","ноль","sıfır (0)","sayı","Температура ноль градусов.","Sıcaklık sıfır derece.");
add("ru","A1","Sayılar","одиннадцать","on bir (11)","sayı","Одиннадцать учеников в классе.","Sınıfta on bir öğrenci var.");
add("ru","A1","Sayılar","двенадцать","on iki (12)","sayı","Двенадцать месяцев в году.","Yılda on iki ay var.");
add("ru","A1","Sayılar","двадцать","yirmi (20)","sayı","Двадцать евро.","Yirmi euro.");
add("ru","A1","Sayılar","тридцать","otuz (30)","sayı","Тридцать минут.","Otuz dakika.");
add("ru","A1","Sayılar","сорок","kırk (40)","sayı","Сорок лет.","Kırk yaşında.");
add("ru","A1","Sayılar","пятьдесят","elli (50)","sayı","Пятьдесят процентов.","Yüzde elli.");
add("ru","A1","Sayılar","сто","yüz (100)","sayı","Сто рублей.","Yüz ruble.");
add("ru","A1","Sayılar","тысяча","bin (1000)","sayı","Тысяча человек.","Bin kişi.");
add("ru","A1","Sayılar","первый","birinci","sayı","Он первый в очереди.","Sırada birinci.");
add("ru","A1","Sayılar","второй","ikinci","sayı","Это второй этаж.","Bu ikinci kat.");
add("ru","A1","Sayılar","третий","üçüncü","sayı","Третий день недели.","Haftanın üçüncü günü.");
add("ru","A1","Aile","семья","aile","isim","Моя семья большая.","Ailem büyük.");
add("ru","A1","Aile","мама","anne","isim","Мама готовит обед.","Anne öğle yemeği hazırlıyor.");
add("ru","A1","Aile","папа","baba","isim","Папа работает.","Baba çalışıyor.");
add("ru","A1","Aile","сын","oğul","isim","Мой сын учится в школе.","Oğlum okulda okuyor.");
add("ru","A1","Aile","дочь","kız evlat","isim","Моя дочь любит рисовать.","Kızım resim yapmayı seviyor.");
add("ru","A1","Aile","брат","erkek kardeş","isim","Мой брат старше меня.","Erkek kardeşim benden büyük.");
add("ru","A1","Aile","сестра","kız kardeş","isim","Моя сестра красивая.","Kız kardeşim güzel.");
add("ru","A1","Aile","бабушка","büyükanne","isim","Бабушка живёт с нами.","Büyükanne bizimle yaşıyor.");
add("ru","A1","Aile","дедушка","büyükbaba","isim","Дедушка рассказывает истории.","Büyükbaba hikayeler anlatıyor.");
add("ru","A1","Aile","муж","koca","isim","Мой муж инженер.","Kocam mühendis.");
add("ru","A1","Aile","жена","eş (kadın)","isim","Его жена врач.","Eşi doktor.");
add("ru","A1","Aile","ребёнок","çocuk","isim","Ребёнок играет во дворе.","Çocuk bahçede oynuyor.");
add("ru","A1","Aile","родители","ebeveynler","isim","Мои родители добрые.","Ebeveynlerim iyi kalpli.");
add("ru","A1","Renkler","красный","kırmızı","sıfat","Флаг красный.","Bayrak kırmızı.");
add("ru","A1","Renkler","синий","mavi","sıfat","Небо синее.","Gökyüzü mavi.");
add("ru","A1","Renkler","зелёный","yeşil","sıfat","Трава зелёная.","Çim yeşil.");
add("ru","A1","Renkler","жёлтый","sarı","sıfat","Солнце жёлтое.","Güneş sarıdır.");
add("ru","A1","Renkler","чёрный","siyah","sıfat","Кот чёрный.","Kedi siyah.");
add("ru","A1","Renkler","белый","beyaz","sıfat","Снег белый.","Kar beyazdır.");
add("ru","A1","Renkler","оранжевый","turuncu","sıfat","Апельсин оранжевый.","Portakal turuncu.");
add("ru","A1","Renkler","розовый","pembe","sıfat","Платье розовое.","Elbise pembe.");
add("ru","A1","Renkler","серый","gri","sıfat","Небо серое сегодня.","Bugün gökyüzü gri.");
add("ru","A1","Renkler","коричневый","kahverengi","sıfat","Стол коричневый.","Masa kahverengi.");
add("ru","A1","Renkler","фиолетовый","mor","sıfat","Цветок фиолетовый.","Çiçek mor.");
add("ru","A1","Günler","понедельник","pazartesi","isim","Понедельник — первый день недели.","Pazartesi haftanın ilk günüdür.");
add("ru","A1","Günler","вторник","salı","isim","Во вторник у меня урок.","Salı günü dersim var.");
add("ru","A1","Günler","среда","çarşamba","isim","Среда — середина недели.","Çarşamba haftanın ortasıdır.");
add("ru","A1","Günler","четверг","perşembe","isim","В четверг мы встретимся.","Perşembe günü buluşacağız.");
add("ru","A1","Günler","пятница","cuma","isim","Пятница — мой любимый день.","Cuma en sevdiğim gün.");
add("ru","A1","Günler","суббота","cumartesi","isim","В субботу я отдыхаю.","Cumartesi dinlenirim.");
add("ru","A1","Günler","воскресенье","pazar","isim","Воскресенье — выходной день.","Pazar tatil günüdür.");
add("ru","A1","Aylar","январь","ocak (ay)","isim","Январь — первый месяц.","Ocak ilk aydır.");
add("ru","A1","Aylar","февраль","şubat","isim","Февраль короткий.","Şubat kısadır.");
add("ru","A1","Aylar","март","mart","isim","Весна начинается в марте.","İlkbahar mart ayında başlar.");
add("ru","A1","Aylar","апрель","nisan","isim","В апреле часто идёт дождь.","Nisan ayında sık yağmur yağar.");
add("ru","A1","Aylar","май","mayıs","isim","Май тёплый.","Mayıs ayı sıcaktır.");
add("ru","A1","Aylar","июнь","haziran","isim","Школа заканчивается в июне.","Okul haziranda bitiyor.");
add("ru","A1","Aylar","июль","temmuz","isim","Июль жаркий месяц.","Temmuz sıcak bir aydır.");
add("ru","A1","Aylar","август","ağustos","isim","В августе мы едем на море.","Ağustosta denize gidiyoruz.");
add("ru","A1","Aylar","сентябрь","eylül","isim","Сентябрь — начало осени.","Eylül sonbaharın başlangıcıdır.");
add("ru","A1","Aylar","октябрь","ekim","isim","В октябре листья падают.","Ekimde yapraklar düşüyor.");
add("ru","A1","Aylar","ноябрь","kasım","isim","Ноябрь холодный.","Kasım soğuktur.");
add("ru","A1","Aylar","декабрь","aralık","isim","Декабрь — последний месяц года.","Aralık yılın son ayıdır.");
add("ru","A1","Mevsimler","весна","ilkbahar","isim","Весна — моё любимое время года.","İlkbahar en sevdiğim mevsim.");
add("ru","A1","Mevsimler","лето","yaz","isim","Лето жаркое.","Yaz sıcaktır.");
add("ru","A1","Mevsimler","осень","sonbahar","isim","Осень красивая.","Sonbahar güzeldir.");
add("ru","A1","Mevsimler","зима","kış","isim","Зимой идёт снег.","Kışın kar yağar.");
add("ru","A1","Yiyecek","хлеб","ekmek","isim","Хлеб свежий.","Ekmek taze.");
add("ru","A1","Yiyecek","вода","su","isim","Вода в стакане.","Bardaktaki su.");
add("ru","A1","Yiyecek","молоко","süt","isim","Молоко холодное.","Süt soğuk.");
add("ru","A1","Yiyecek","чай","çay","isim","Я пью чай утром.","Sabah çay içerim.");
add("ru","A1","Yiyecek","кофе","kahve","isim","Кофе горячий.","Kahve sıcak.");
add("ru","A1","Yiyecek","сахар","şeker","isim","Сахар сладкий.","Şeker tatlıdır.");
add("ru","A1","Yiyecek","соль","tuz","isim","Дай мне соль.","Bana tuzu ver.");
add("ru","A1","Yiyecek","мясо","et","isim","Мясо вкусное.","Et lezzetli.");
add("ru","A1","Yiyecek","рыба","balık","isim","Рыба свежая.","Balık taze.");
add("ru","A1","Yiyecek","рис","pirinç","isim","Я готовлю рис.","Pirinç pişiriyorum.");
add("ru","A1","Yiyecek","суп","çorba","isim","Суп горячий.","Çorba sıcak.");
add("ru","A1","Yiyecek","салат","salata","isim","Салат свежий.","Salata taze.");
add("ru","A1","Yiyecek","яйцо","yumurta","isim","Я ем яйцо на завтрак.","Kahvaltıda yumurta yerim.");
add("ru","A1","Yiyecek","сыр","peynir","isim","Сыр вкусный.","Peynir lezzetli.");
add("ru","A1","Yiyecek","масло","tereyağı","isim","Намажь масло на хлеб.","Ekmeğe tereyağı sür.");
add("ru","A1","Yiyecek","мёд","bal","isim","Мёд сладкий.","Bal tatlı.");
add("ru","A1","Yiyecek","завтрак","kahvaltı","isim","Завтрак готов.","Kahvaltı hazır.");
add("ru","A1","Yiyecek","обед","öğle yemeği","isim","Обед был вкусным.","Öğle yemeği lezzetliydi.");
add("ru","A1","Yiyecek","ужин","akşam yemeği","isim","Ужин готов.","Akşam yemeği hazır.");
add("ru","A1","Meyve ve Sebze","яблоко","elma","isim","Яблоко красное.","Elma kırmızı.");
add("ru","A1","Meyve ve Sebze","банан","muz","isim","Банан жёлтый.","Muz sarıdır.");
add("ru","A1","Meyve ve Sebze","апельсин","portakal","isim","Апельсин сладкий.","Portakal tatlıdır.");
add("ru","A1","Meyve ve Sebze","виноград","üzüm","isim","Виноград сладкий.","Üzüm tatlıdır.");
add("ru","A1","Meyve ve Sebze","картофель","patates","isim","Я готовлю картофель.","Patates pişiriyorum.");
add("ru","A1","Meyve ve Sebze","лук","soğan","isim","Лук заставляет меня плакать.","Soğan beni ağlatıyor.");
add("ru","A1","Meyve ve Sebze","морковь","havuç","isim","Морковь полезная.","Havuç faydalıdır.");
add("ru","A1","Meyve ve Sebze","помидор","domates","isim","Помидор красный.","Domates kırmızı.");
add("ru","A1","Meyve ve Sebze","огурец","salatalık","isim","Огурец свежий.","Salatalık taze.");
add("ru","A1","Hayvanlar","собака","köpek","isim","Собака бежит.","Köpek koşuyor.");
add("ru","A1","Hayvanlar","кошка","kedi","isim","Кошка спит.","Kedi uyuyor.");
add("ru","A1","Hayvanlar","птица","kuş","isim","Птица летает.","Kuş uçuyor.");
add("ru","A1","Hayvanlar","лошадь","at","isim","Лошадь бежит быстро.","At hızlı koşuyor.");
add("ru","A1","Hayvanlar","корова","inek","isim","Корова даёт молоко.","İnek süt verir.");
add("ru","A1","Hayvanlar","рыба (животное)","balık (hayvan)","isim","В реке много рыбы.","Nehirde çok balık var.");
add("ru","A1","Hayvanlar","заяц","tavşan","isim","Заяц быстрый.","Tavşan hızlıdır.");
add("ru","A1","Hayvanlar","медведь","ayı","isim","Медведь спит зимой.","Ayı kışın uyur.");
add("ru","A1","Vücut","голова","baş / kafa","isim","Голова болит.","Başım ağrıyor.");
add("ru","A1","Vücut","глаз","göz","isim","У неё голубые глаза.","Mavi gözleri var.");
add("ru","A1","Vücut","нос","burun","isim","Нос маленький.","Burun küçük.");
add("ru","A1","Vücut","рот","ağız","isim","Открой рот.","Ağzını aç.");
add("ru","A1","Vücut","ухо","kulak","isim","Ухо болит.","Kulağım ağrıyor.");
add("ru","A1","Vücut","рука","el / kol","isim","Моя рука болит.","Elim ağrıyor.");
add("ru","A1","Vücut","нога","ayak / bacak","isim","Нога болит.","Bacağım ağrıyor.");
add("ru","A1","Vücut","живот","karın","isim","Живот болит.","Karnım ağrıyor.");
add("ru","A1","Vücut","спина","sırt","isim","Спина болит.","Sırtım ağrıyor.");
add("ru","A1","Vücut","волосы","saçlar","isim","У неё длинные волосы.","Saçları uzun.");
add("ru","A1","Vücut","зуб","diş","isim","Зуб болит.","Diş ağrıyor.");
add("ru","A1","Vücut","сердце","kalp","isim","Сердце бьётся быстро.","Kalp hızlı atıyor.");
add("ru","A1","Giysi","одежда","kıyafet","isim","Моя одежда чистая.","Kıyafetlerim temiz.");
add("ru","A1","Giysi","рубашка","gömlek","isim","Рубашка белая.","Gömlek beyaz.");
add("ru","A1","Giysi","брюки","pantolon","isim","Брюки новые.","Pantolon yeni.");
add("ru","A1","Giysi","платье","elbise","isim","Платье красивое.","Elbise güzel.");
add("ru","A1","Giysi","юбка","etek","isim","Юбка новая.","Etek yeni.");
add("ru","A1","Giysi","куртка","ceket","isim","Куртка тёплая.","Ceket sıcak.");
add("ru","A1","Giysi","обувь","ayakkabı","isim","Обувь удобная.","Ayakkabı rahat.");
add("ru","A1","Giysi","шапка","şapka / bere","isim","Шапка тёплая.","Şapka sıcak.");
add("ru","A1","Giysi","носки","çoraplar","isim","Носки чистые.","Çoraplar temiz.");
add("ru","A1","Ev","дом","ev","isim","Мой дом большой.","Evim büyük.");
add("ru","A1","Ev","квартира","daire","isim","Квартира маленькая.","Daire küçük.");
add("ru","A1","Ev","комната","oda","isim","Комната светлая.","Oda aydınlık.");
add("ru","A1","Ev","кухня","mutfak","isim","Кухня чистая.","Mutfak temiz.");
add("ru","A1","Ev","спальня","yatak odası","isim","Спальня уютная.","Yatak odası rahat.");
add("ru","A1","Ev","ванная","banyo","isim","Ванная маленькая.","Banyo küçük.");
add("ru","A1","Ev","дверь","kapı","isim","Дверь открыта.","Kapı açık.");
add("ru","A1","Ev","окно","pencere","isim","Окно закрыто.","Pencere kapalı.");
add("ru","A1","Ev Eşyaları","стол","masa","isim","Стол большой.","Masa büyük.");
add("ru","A1","Ev Eşyaları","стул","sandalye","isim","Стул удобный.","Sandalye rahat.");
add("ru","A1","Ev Eşyaları","кровать","yatak","isim","Кровать мягкая.","Yatak yumuşak.");
add("ru","A1","Ev Eşyaları","шкаф","dolap","isim","Шкаф большой.","Dolap büyük.");
add("ru","A1","Ev Eşyaları","лампа","lamba","isim","Лампа яркая.","Lamba parlak.");
add("ru","A1","Eylemler","быть","olmak","fiil","Я хочу быть врачом.","Doktor olmak istiyorum.");
add("ru","A1","Eylemler","иметь","sahip olmak","fiil","У меня есть машина.","Bir arabam var.");
add("ru","A1","Eylemler","делать","yapmak","fiil","Что ты делаешь?","Ne yapıyorsun?");
add("ru","A1","Eylemler","идти","gitmek","fiil","Я иду домой.","Eve gidiyorum.");
add("ru","A1","Eylemler","приходить","gelmek","fiil","Он придёт завтра.","Yarın gelecek.");
add("ru","A1","Eylemler","видеть","görmek","fiil","Я вижу тебя.","Seni görüyorum.");
add("ru","A1","Eylemler","слышать","duymak","fiil","Я слышу музыку.","Müzik duyuyorum.");
add("ru","A1","Eylemler","говорить","konuşmak","fiil","Он говорит по-русски.","Rusça konuşuyor.");
add("ru","A1","Eylemler","знать","bilmek","fiil","Я знаю ответ.","Cevabı biliyorum.");
add("ru","A1","Eylemler","понимать","anlamak","fiil","Я не понимаю.","Anlamıyorum.");
add("ru","A1","Eylemler","думать","düşünmek","fiil","Я думаю о тебе.","Seni düşünüyorum.");
add("ru","A1","Eylemler","хотеть","istemek","fiil","Я хочу чай.","Çay istiyorum.");
add("ru","A1","Eylemler","любить","sevmek","fiil","Я люблю тебя.","Seni seviyorum.");
add("ru","A1","Eylemler","есть (кушать)","yemek yemek","fiil","Я хочу есть.","Yemek istiyorum.");
add("ru","A1","Eylemler","пить","içmek","fiil","Я пью воду.","Su içiyorum.");
add("ru","A1","Eylemler","спать","uyumak","fiil","Ребёнок спит.","Çocuk uyuyor.");
add("ru","A1","Eylemler","работать","çalışmak","fiil","Я работаю в офисе.","Ofiste çalışıyorum.");
add("ru","A1","Eylemler","учиться","öğrenmek / okumak","fiil","Я учусь в университете.","Üniversitede okuyorum.");
add("ru","A1","Eylemler","жить","yaşamak","fiil","Я живу в Москве.","Moskova'da yaşıyorum.");
add("ru","A1","Eylemler","читать","okumak (kitap)","fiil","Я читаю книгу.","Bir kitap okuyorum.");
add("ru","A1","Eylemler","писать","yazmak","fiil","Я пишу письмо.","Bir mektup yazıyorum.");
add("ru","A1","Eylemler","смотреть","bakmak / izlemek","fiil","Я смотрю фильм.","Bir film izliyorum.");
add("ru","A1","Eylemler","играть","oynamak","fiil","Дети играют.","Çocuklar oynuyor.");
add("ru","A1","Eylemler","покупать","satın almak","fiil","Я покупаю хлеб.","Ekmek satın alıyorum.");
add("ru","A1","Eylemler","открывать","açmak","fiil","Открой дверь.","Kapıyı aç.");
add("ru","A1","Eylemler","закрывать","kapatmak","fiil","Закрой окно.","Pencereyi kapat.");
add("ru","A1","Eylemler","давать","vermek","fiil","Дай мне книгу.","Bana kitabı ver.");
add("ru","A1","Eylemler","брать","almak","fiil","Возьми деньги.","Parayı al.");
add("ru","A1","Sıfatlar","хороший","iyi","sıfat","Это хороший день.","Bu iyi bir gün.");
add("ru","A1","Sıfatlar","плохой","kötü","sıfat","Это плохая идея.","Bu kötü bir fikir.");
add("ru","A1","Sıfatlar","большой","büyük","sıfat","Дом большой.","Ev büyük.");
add("ru","A1","Sıfatlar","маленький","küçük","sıfat","Кот маленький.","Kedi küçük.");
add("ru","A1","Sıfatlar","новый","yeni","sıfat","Телефон новый.","Telefon yeni.");
add("ru","A1","Sıfatlar","старый","eski / yaşlı","sıfat","Книга старая.","Kitap eski.");
add("ru","A1","Sıfatlar","красивый","güzel","sıfat","Город красивый.","Şehir güzel.");
add("ru","A1","Sıfatlar","дорогой","pahalı","sıfat","Машина дорогая.","Araba pahalı.");
add("ru","A1","Sıfatlar","дешёвый","ucuz","sıfat","Книга дешёвая.","Kitap ucuz.");
add("ru","A1","Sıfatlar","тяжёлый","ağır","sıfat","Чемодан тяжёлый.","Valiz ağır.");
add("ru","A1","Sıfatlar","лёгкий","hafif / kolay","sıfat","Сумка лёгкая.","Çanta hafif.");
add("ru","A1","Sıfatlar","горячий","sıcak (sıvı/nesne)","sıfat","Чай горячий.","Çay sıcak.");
add("ru","A1","Sıfatlar","холодный","soğuk","sıfat","Вода холодная.","Su soğuk.");
add("ru","A1","Sıfatlar","быстрый","hızlı","sıfat","Он быстрый бегун.","O hızlı bir koşucu.");
add("ru","A1","Sıfatlar","медленный","yavaş","sıfat","Черепаха медленная.","Kaplumbağa yavaş.");
add("ru","A1","Zamirler","я","ben","zamir","Я студент.","Ben öğrenciyim.");
add("ru","A1","Zamirler","ты","sen","zamir","Ты мой друг.","Sen benim arkadaşımsın.");
add("ru","A1","Zamirler","он","o (erkek)","zamir","Он врач.","O doktor.");
add("ru","A1","Zamirler","она","o (kadın)","zamir","Она учительница.","O öğretmen.");
add("ru","A1","Zamirler","мы","biz","zamir","Мы друзья.","Biz arkadaşız.");
add("ru","A1","Zamirler","вы","siz","zamir","Вы правы.","Haklısınız.");
add("ru","A1","Zamirler","они","onlar","zamir","Они студенты.","Onlar öğrenci.");
add("ru","A1","Zamirler","мой","benim","zamir","Это мой дом.","Bu benim evim.");
add("ru","A1","Zamirler","твой","senin","zamir","Это твоя книга?","Bu senin kitabın mı?");
add("ru","A1","Zamirler","это","bu","zamir","Это моя сумка.","Bu benim çantam.");
add("ru","A1","Zamirler","то","şu","zamir","То дерево большое.","Şu ağaç büyük.");
add("ru","A1","Sorular","что","ne","soru zamiri","Что это?","Bu nedir?");
add("ru","A1","Sorular","кто","kim","soru zamiri","Кто ты?","Sen kimsin?");
add("ru","A1","Sorular","где","nerede","soru zamiri","Где ты живёшь?","Nerede yaşıyorsun?");
add("ru","A1","Sorular","когда","ne zaman","soru zamiri","Когда ты придёшь?","Ne zaman geleceksin?");
add("ru","A1","Sorular","почему","neden","soru zamiri","Почему ты грустишь?","Neden üzgünsün?");
add("ru","A1","Sorular","как","nasıl","soru zamiri","Как дела?","Nasılsın?");
add("ru","A1","Sorular","сколько","kaç / ne kadar","soru zamiri","Сколько это стоит?","Bu ne kadar?");
add("ru","A1","Sorular","какой","hangi","soru zamiri","Какой цвет ты любишь?","Hangi rengi seviyorsun?");
add("ru","A1","Edatlar","в","içinde / -de","edat","Книга в сумке.","Kitap çantada.");
add("ru","A1","Edatlar","на","üzerinde","edat","Чашка на столе.","Fincan masanın üzerinde.");
add("ru","A1","Edatlar","под","altında","edat","Кот под столом.","Kedi masanın altında.");
add("ru","A1","Edatlar","с","ile / -le","edat","Я иду с другом.","Arkadaşımla gidiyorum.");
add("ru","A1","Edatlar","без","-sız","edat","Кофе без сахара.","Şekersiz kahve.");
add("ru","A1","Edatlar","для","için","edat","Это подарок для тебя.","Bu senin için bir hediye.");
add("ru","A1","Edatlar","от","-den","edat","Письмо от мамы.","Anneden bir mektup.");
add("ru","A1","Edatlar","до","-e kadar","edat","От дома до школы.","Evden okula kadar.");
add("ru","A1","Bağlaçlar","и","ve","bağlaç","Я и ты.","Ben ve sen.");
add("ru","A1","Bağlaçlar","или","veya","bağlaç","Чай или кофе?","Çay veya kahve?");
add("ru","A1","Bağlaçlar","но","ama","bağlaç","Я хочу, но не могу.","İstiyorum ama yapamam.");
add("ru","A1","Bağlaçlar","потому что","çünkü","bağlaç","Я устал, потому что много работал.","Yorgunum çünkü çok çalıştım.");
add("ru","A1","Zaman","сегодня","bugün","zarf","Сегодня хорошая погода.","Bugün hava güzel.");
add("ru","A1","Zaman","завтра","yarın","zarf","Завтра будет дождь.","Yarın yağmur yağacak.");
add("ru","A1","Zaman","вчера","dün","zarf","Вчера я работал.","Dün çalıştım.");
add("ru","A1","Zaman","сейчас","şimdi","zarf","Я занят сейчас.","Şimdi meşgulüm.");
add("ru","A1","Zaman","потом","sonra","zarf","Потом поговорим.","Sonra konuşuruz.");
add("ru","A1","Zaman","утро","sabah","isim","Утро прохладное.","Sabah serin.");
add("ru","A1","Zaman","день (время суток)","gündüz","isim","День солнечный.","Gündüz güneşli.");
add("ru","A1","Zaman","вечер","akşam","isim","Вечер тихий.","Akşam sakin.");
add("ru","A1","Zaman","ночь","gece","isim","Ночь тёмная.","Gece karanlık.");
add("ru","A1","Meslekler","врач","doktor","isim","Врач лечит людей.","Doktor insanları tedavi eder.");
add("ru","A1","Meslekler","учитель","öğretmen","isim","Учитель объясняет урок.","Öğretmen dersi anlatıyor.");
add("ru","A1","Meslekler","инженер","mühendis","isim","Инженер строит мосты.","Mühendis köprüler inşa ediyor.");
add("ru","A1","Meslekler","студент","öğrenci (üniversite)","isim","Студент учится в университете.","Öğrenci üniversitede okuyor.");
add("ru","A1","Meslekler","полицейский","polis","isim","Полицейский помогает людям.","Polis insanlara yardım ediyor.");
add("ru","A1","Meslekler","повар","aşçı","isim","Повар готовит обед.","Aşçı yemek hazırlıyor.");
add("ru","A1","Meslekler","водитель","şoför","isim","Водитель ведёт машину.","Şoför arabayı sürüyor.");
add("ru","A1","Meslekler","продавец","satıcı","isim","Продавец в магазине.","Satıcı dükkanda.");
add("ru","A1","Ulaşım","машина","araba","isim","Машина новая.","Araba yeni.");
add("ru","A1","Ulaşım","автобус","otobüs","isim","Автобус опаздывает.","Otobüs gecikiyor.");
add("ru","A1","Ulaşım","поезд","tren","isim","Поезд быстрый.","Tren hızlı.");
add("ru","A1","Ulaşım","самолёт","uçak","isim","Самолёт летит высоко.","Uçak yükseğe uçuyor.");
add("ru","A1","Ulaşım","велосипед","bisiklet","isim","Я катаюсь на велосипеде.","Bisiklete biniyorum.");
add("ru","A1","Ulaşım","такси","taksi","isim","Я взял такси.","Bir taksiye bindim.");
add("ru","A1","Ulaşım","метро","metro","isim","Метро быстрое.","Metro hızlı.");
add("ru","A1","Ulaşım","улица","sokak","isim","Улица длинная.","Sokak uzun.");
add("ru","A1","Ulaşım","дорога","yol","isim","Дорога к морю длинная.","Denize giden yol uzun.");
add("ru","A1","Okul","школа","okul","isim","Школа рядом.","Okul yakında.");
add("ru","A1","Okul","университет","üniversite","isim","Университет большой.","Üniversite büyük.");
add("ru","A1","Okul","класс","sınıf","isim","Класс большой.","Sınıf kalabalık.");
add("ru","A1","Okul","урок","ders","isim","Урок интересный.","Ders ilginç.");
add("ru","A1","Okul","книга","kitap","isim","Книга интересная.","Kitap ilginç.");
add("ru","A1","Okul","ручка","kalem (tükenmez)","isim","Ручка синяя.","Kalem mavi.");
add("ru","A1","Okul","тетрадь","defter","isim","Тетрадь новая.","Defter yeni.");
add("ru","A1","Okul","учитель (2)","öğretmen (2)","isim","Учитель строгий.","Öğretmen katı.");
add("ru","A1","Yerler","город","şehir","isim","Город большой.","Şehir büyük.");
add("ru","A1","Yerler","деревня","köy","isim","Деревня тихая.","Köy sakin.");
add("ru","A1","Yerler","магазин","dükkan / mağaza","isim","Магазин открыт.","Mağaza açık.");
add("ru","A1","Yerler","парк","park","isim","Парк зелёный.","Park yeşil.");
add("ru","A1","Yerler","ресторан","restoran","isim","Ресторан дорогой.","Restoran pahalı.");
add("ru","A1","Yerler","больница","hastane","isim","Больница большая.","Hastane büyük.");
add("ru","A1","Genel","телефон","telefon","isim","Мой телефон новый.","Telefonum yeni.");
add("ru","A1","Genel","деньги","para","isim","У меня нет денег.","Param yok.");
add("ru","A1","Genel","время","zaman","isim","У меня нет времени.","Zamanım yok.");
add("ru","A1","Genel","имя","isim (ad)","isim","Как твоё имя?","İsmin ne?");
add("ru","A2","Ev İşleri","убирать","temizlemek","fiil","Я убираю комнату.","Odayı temizliyorum.");
add("ru","A2","Ev İşleri","готовить","yemek pişirmek","fiil","Мама готовит ужин.","Anne akşam yemeği pişiriyor.");
add("ru","A2","Ev İşleri","мыть","yıkamak","fiil","Я мою посуду.","Bulaşık yıkıyorum.");
add("ru","A2","Ev İşleri","стирать","çamaşır yıkamak","fiil","Я стираю одежду.","Kıyafet yıkıyorum.");
add("ru","A2","Ev İşleri","гладить","ütülemek","fiil","Я глажу рубашку.","Gömleği ütülüyorum.");
add("ru","A2","Ev İşleri","пылесосить","elektrikli süpürgeyle temizlemek","fiil","Я пылесошу гостиную.","Oturma odasını süpürüyorum.");
add("ru","A2","Hobiler","хобби","hobi","isim","Моё хобби — рисование.","Hobim resim yapmak.");
add("ru","A2","Hobiler","рисовать","resim yapmak","fiil","Она любит рисовать.","Resim yapmayı seviyor.");
add("ru","A2","Hobiler","петь","şarkı söylemek","fiil","Он любит петь.","Şarkı söylemeyi seviyor.");
add("ru","A2","Hobiler","танцевать","dans etmek","fiil","Она хорошо танцует.","İyi dans ediyor.");
add("ru","A2","Hobiler","плавать","yüzmek","fiil","Он хорошо плавает.","İyi yüzüyor.");
add("ru","A2","Hobiler","путешествовать","seyahat etmek","fiil","Я люблю путешествовать.","Seyahat etmeyi severim.");
add("ru","A2","Hobiler","фотографировать","fotoğraf çekmek","fiil","Он любит фотографировать.","Fotoğraf çekmeyi seviyor.");
add("ru","A2","Hobiler","коллекционировать","koleksiyon yapmak","fiil","Он коллекционирует марки.","Pul koleksiyonu yapıyor.");
add("ru","A2","Spor","футбол","futbol","isim","Он играет в футбол.","Futbol oynuyor.");
add("ru","A2","Spor","баскетбол","basketbol","isim","Баскетбол — мой любимый спорт.","Basketbol en sevdiğim spor.");
add("ru","A2","Spor","теннис","tenis","isim","Он играет в теннис.","Tenis oynuyor.");
add("ru","A2","Spor","бегать","koşmak","fiil","Я бегаю каждое утро.","Her sabah koşarım.");
add("ru","A2","Spor","тренировка","antrenman","isim","Тренировка была тяжёлой.","Antrenman zordu.");
add("ru","A2","Spor","команда","takım","isim","Наша команда выиграла.","Takımımız kazandı.");
add("ru","A2","Duygular","счастливый","mutlu","sıfat","Я счастлив.","Mutluyum.");
add("ru","A2","Duygular","грустный","üzgün","sıfat","Он грустный.","O üzgün.");
add("ru","A2","Duygular","злой","kızgın","sıfat","Она злая.","O kızgın.");
add("ru","A2","Duygular","усталый","yorgun","sıfat","Я устал.","Yorgunum.");
add("ru","A2","Duygular","удивлённый","şaşırmış","sıfat","Он удивлённый.","O şaşırmış.");
add("ru","A2","Duygular","испуганный","korkmuş","sıfat","Ребёнок испуганный.","Çocuk korkmuş.");
add("ru","A2","Duygular","влюблённый","aşık","sıfat","Он влюблён.","O aşık.");
add("ru","A2","Duygular","радость","sevinç","isim","Радость наполняет сердце.","Sevinç kalbi dolduruyor.");
add("ru","A2","Duygular","страх","korku","isim","Страх — нормальное чувство.","Korku normal bir duygudur.");
add("ru","A2","Duygular","любовь","aşk","isim","Любовь — прекрасное чувство.","Aşk güzel bir duygudur.");
add("ru","A2","Sağlık","болезнь","hastalık","isim","Это серьёзная болезнь.","Bu ciddi bir hastalık.");
add("ru","A2","Sağlık","больной","hasta","sıfat","Он болен.","O hasta.");
add("ru","A2","Sağlık","здоровый","sağlıklı","sıfat","Она здорова.","O sağlıklı.");
add("ru","A2","Sağlık","боль","ağrı","isim","У меня боль в голове.","Baş ağrım var.");
add("ru","A2","Sağlık","лекарство","ilaç","isim","Прими лекарство.","İlacı al.");
add("ru","A2","Sağlık","аптека","eczane","isim","Аптека рядом.","Eczane yakında.");
add("ru","A2","Sağlık","температура (жар)","ateş (vücut)","isim","У ребёнка температура.","Çocuğun ateşi var.");
add("ru","A2","Sağlık","кашель","öksürük","isim","У него сильный кашель.","Şiddetli öksürüğü var.");
add("ru","A2","Sağlık","простуда","soğuk algınlığı","isim","У меня простуда.","Soğuk algınlığım var.");
add("ru","A2","Alışveriş","цена","fiyat","isim","Цена высокая.","Fiyat yüksek.");
add("ru","A2","Alışveriş","скидка","indirim","isim","Есть скидка.","Bir indirim var.");
add("ru","A2","Alışveriş","касса","kasa","isim","Иди к кассе.","Kasaya git.");
add("ru","A2","Alışveriş","чек","fiş","isim","Дайте мне чек.","Bana bir fiş verin.");
add("ru","A2","Alışveriş","размер","beden / boyut","isim","Какой у вас размер?","Bedeniniz nedir?");
add("ru","A2","Alışveriş","примерочная","soyunma kabini","isim","Где примерочная?","Soyunma kabini nerede?");
add("ru","A2","Hava Durumu","погода","hava (durumu)","isim","Какая сегодня погода?","Bugün hava nasıl?");
add("ru","A2","Hava Durumu","солнце","güneş","isim","Солнце светит.","Güneş parlıyor.");
add("ru","A2","Hava Durumu","дождь","yağmur","isim","Идёт дождь.","Yağmur yağıyor.");
add("ru","A2","Hava Durumu","снег","kar","isim","Идёт снег.","Kar yağıyor.");
add("ru","A2","Hava Durumu","ветер","rüzgar","isim","Дует сильный ветер.","Güçlü rüzgar esiyor.");
add("ru","A2","Hava Durumu","облако","bulut","isim","Облако серое.","Bulut gri.");
add("ru","A2","Hava Durumu","жарко","sıcak (hava)","sıfat","Сегодня жарко.","Bugün hava sıcak.");
add("ru","A2","Hava Durumu","холодно","soğuk (hava)","sıfat","Сегодня холодно.","Bugün hava soğuk.");
add("ru","A2","Ülkeler ve Milliyetler","Россия","Rusya","isim","Россия очень большая.","Rusya çok büyüktür.");
add("ru","A2","Ülkeler ve Milliyetler","Турция","Türkiye","isim","Турция красивая страна.","Türkiye güzel bir ülke.");
add("ru","A2","Ülkeler ve Milliyetler","Германия","Almanya","isim","Германия в Европе.","Almanya Avrupa'dadır.");
add("ru","A2","Ülkeler ve Milliyetler","Америка","Amerika","isim","Америка далеко.","Amerika uzaktır.");
add("ru","A2","İlişkiler","друг","arkadaş (erkek)","isim","Он мой друг.","O benim arkadaşım.");
add("ru","A2","İlişkiler","подруга","arkadaş (kadın)","isim","Она моя подруга.","O benim arkadaşım.");
add("ru","A2","İlişkiler","сосед","komşu","isim","Мой сосед добрый.","Komşum iyi kalpli.");
add("ru","A2","Eylemler","начинать","başlamak","fiil","Урок начинается в девять.","Ders dokuzda başlıyor.");
add("ru","A2","Eylemler","заканчивать","bitirmek","fiil","Я заканчиваю работу в пять.","İşimi beşte bitiriyorum.");
add("ru","A2","Eylemler","помогать","yardım etmek","fiil","Я помогаю маме.","Anneme yardım ediyorum.");
add("ru","A2","Eylemler","встречать","karşılamak / tanışmak","fiil","Я встречаю друга.","Bir arkadaşla tanışıyorum.");
add("ru","A2","Eylemler","звонить","aramak (telefon)","fiil","Я звоню маме.","Anneyi arıyorum.");
add("ru","A2","Eylemler","искать","aramak (bulmak)","fiil","Я ищу ключи.","Anahtarları arıyorum.");
add("ru","A2","Eylemler","находить","bulmak","fiil","Я нашёл ключи.","Anahtarları buldum.");
add("ru","A2","Eylemler","терять","kaybetmek","fiil","Я потерял телефон.","Telefonumu kaybettim.");
add("ru","A2","Eylemler","забывать","unutmak","fiil","Я забыл имя.","İsmi unuttum.");
add("ru","A2","Eylemler","вспоминать","hatırlamak","fiil","Я вспоминаю детство.","Çocukluğumu hatırlıyorum.");
add("ru","A2","Eylemler","ждать","beklemek","fiil","Я жду тебя.","Seni bekliyorum.");
add("ru","A2","Eylemler","приезжать","gelmek (varmak)","fiil","Поезд приезжает вовремя.","Tren zamanında geliyor.");
add("ru","A2","Eylemler","уезжать","gitmek (ayrılmak)","fiil","Он уезжает завтра.","Yarın gidiyor.");
add("ru","A2","Eylemler","возвращаться","geri dönmek","fiil","Я возвращаюсь домой.","Eve geri dönüyorum.");
add("ru","A2","Eylemler","путешествовать (2)","seyahat etmek (2)","fiil","Мы путешествуем каждое лето.","Her yaz seyahat ediyoruz.");
add("ru","A2","Eylemler","спрашивать","sormak","fiil","Я спрашиваю дорогу.","Yolu soruyorum.");
add("ru","A2","Eylemler","отвечать","cevaplamak","fiil","Я отвечаю на вопрос.","Soruyu cevaplıyorum.");
add("ru","A2","Eylemler","объяснять","açıklamak","fiil","Учитель объясняет тему.","Öğretmen konuyu açıklıyor.");
add("ru","A2","Eylemler","решать","karar vermek / çözmek","fiil","Я решил проблему.","Sorunu çözdüm.");
add("ru","A2","Eylemler","пробовать","denemek","fiil","Я пробую новую еду.","Yeni bir yemek deniyorum.");
add("ru","A2","Zarflar","всегда","her zaman","zarf","Она всегда добрая.","Her zaman iyi kalpli.");
add("ru","A2","Zarflar","никогда","asla","zarf","Я никогда не лгу.","Asla yalan söylemem.");
add("ru","A2","Zarflar","иногда","bazen","zarf","Иногда идёт дождь.","Bazen yağmur yağar.");
add("ru","A2","Zarflar","часто","sık sık","zarf","Он часто путешествует.","Sık sık seyahat eder.");
add("ru","A2","Zarflar","редко","nadiren","zarf","Он редко звонит.","Nadiren arar.");
add("ru","A2","Zarflar","уже","zaten / şimdiden","zarf","Я уже поел.","Zaten yedim.");
add("ru","A2","Zarflar","ещё","henüz / hâlâ","zarf","Я ещё не готов.","Henüz hazır değilim.");
add("ru","A2","Zarflar","очень","çok (zarf)","zarf","Это очень интересно.","Bu çok ilginç.");
add("ru","A2","Zarflar","немного","biraz","zarf","Дай мне немного воды.","Bana biraz su ver.");
add("ru","A2","Zarflar","вместе","birlikte","zarf","Мы работаем вместе.","Birlikte çalışıyoruz.");
add("ru","A2","Sıfatlar","умный","zeki / akıllı","sıfat","Он очень умный.","O çok zeki.");
add("ru","A2","Sıfatlar","глупый","aptal","sıfat","Это глупая идея.","Bu aptalca bir fikir.");
add("ru","A2","Sıfatlar","сильный","güçlü","sıfat","Он сильный.","O güçlü.");
add("ru","A2","Sıfatlar","слабый","zayıf","sıfat","Она чувствует себя слабой.","Kendini zayıf hissediyor.");
add("ru","A2","Sıfatlar","высокий","uzun (boy) / yüksek","sıfat","Он высокий.","O uzun boylu.");
add("ru","A2","Sıfatlar","низкий","alçak / kısa","sıfat","Потолок низкий.","Tavan alçak.");
add("ru","A2","Sıfatlar","длинный","uzun (nesne)","sıfat","Дорога длинная.","Yol uzun.");
add("ru","A2","Sıfatlar","короткий","kısa","sıfat","Юбка короткая.","Etek kısa.");
add("ru","A2","Sıfatlar","широкий","geniş","sıfat","Улица широкая.","Sokak geniş.");
add("ru","A2","Sıfatlar","узкий","dar","sıfat","Улица узкая.","Sokak dar.");
add("ru","A2","Sıfatlar","полный","dolu","sıfat","Стакан полный.","Bardak dolu.");
add("ru","A2","Sıfatlar","пустой","boş","sıfat","Комната пустая.","Oda boş.");
add("ru","A2","Sıfatlar","чистый","temiz","sıfat","Комната чистая.","Oda temiz.");
add("ru","A2","Sıfatlar","грязный","kirli","sıfat","Одежда грязная.","Kıyafetler kirli.");
add("ru","A2","Sıfatlar","интересный","ilginç","sıfat","Фильм интересный.","Film ilginç.");
add("ru","A2","Sıfatlar","скучный","sıkıcı","sıfat","Урок скучный.","Ders sıkıcı.");
add("ru","A2","Sıfatlar","важный","önemli","sıfat","Это важно.","Bu önemli.");
add("ru","A2","Sıfatlar","опасный","tehlikeli","sıfat","Это опасно.","Bu tehlikeli.");
add("ru","A2","Sıfatlar","лёгкий (2)","kolay (2)","sıfat","Задача лёгкая.","Görev kolay.");
add("ru","A2","Sıfatlar","трудный","zor","sıfat","Экзамен трудный.","Sınav zor.");
add("ru","A2","Deyimler","Не за что","bir şey değil","ifade","Спасибо! — Не за что.","Teşekkürler! — Bir şey değil.");
add("ru","A2","Deyimler","Всё в порядке","her şey yolunda","ifade","Не волнуйся, всё в порядке.","Endişelenme, her şey yolunda.");
add("ru","A2","Deyimler","Я не знаю","bilmiyorum","ifade","Извини, я не знаю.","Üzgünüm, bilmiyorum.");
add("ru","A2","Deyimler","Я согласен","katılıyorum","ifade","Я полностью согласен.","Tamamen katılıyorum.");
add("ru","A2","Deyimler","Я не согласен","katılmıyorum","ifade","Извини, я не согласен.","Üzgünüm, katılmıyorum.");
add("ru","A2","Deyimler","Конечно","tabii ki","ifade","Конечно, я помогу.","Tabii ki yardım ederim.");
add("ru","A2","Deyimler","Может быть","belki","ifade","Может быть, завтра.","Belki yarın.");
add("ru","A2","Deyimler","С удовольствием","memnuniyetle","ifade","С удовольствием помогу.","Memnuniyetle yardım ederim.");
add("ru","A2","Deyimler","Не переживай","üzülme / dert etme","ifade","Не переживай об этом.","Bunun için dert etme.");
add("ru","A2","Teknoloji","компьютер","bilgisayar","isim","Мой компьютер новый.","Bilgisayarım yeni.");
add("ru","A2","Teknoloji","интернет","internet","isim","Интернет медленный.","İnternet yavaş.");
add("ru","A2","Teknoloji","телефон (2)","telefon (2)","isim","Мой телефон сломан.","Telefonum bozuk.");
add("ru","A2","Teknoloji","приложение","uygulama","isim","Это приложение полезное.","Bu uygulama faydalı.");
add("ru","A2","Teknoloji","пароль","şifre","isim","Я забыл пароль.","Şifremi unuttum.");
add("ru","A2","İletişim","сообщение","mesaj","isim","Я отправил сообщение.","Bir mesaj gönderdim.");
add("ru","A2","İletişim","письмо","mektup / e-posta","isim","Я написал письмо.","Bir mektup yazdım.");
add("ru","A2","İletişim","разговор","konuşma / sohbet","isim","Разговор был долгим.","Konuşma uzundu.");
add("ru","A2","İletişim","новости","haberler","isim","Новости важные.","Haberler önemlidir.");
add("ru","A2","Ekonomi","банк","banka","isim","Банк закрыт.","Banka kapalı.");
add("ru","A2","Ekonomi","счёт (банк)","hesap (banka)","isim","Мой счёт пуст.","Hesabım boş.");
add("ru","A2","Ekonomi","зарплата","maaş","isim","Зарплата хорошая.","Maaş iyi.");
add("ru","A2","İş ve Kariyer","работа","iş","isim","Я иду на работу.","İşe gidiyorum.");
add("ru","A2","İş ve Kariyer","офис","ofis","isim","Мой офис маленький.","Ofisim küçük.");
add("ru","A2","İş ve Kariyer","начальник","patron","isim","Мой начальник строгий.","Patronum katı.");
add("ru","A2","İş ve Kariyer","коллега","iş arkadaşı","isim","Мой коллега помогает мне.","İş arkadaşım bana yardım ediyor.");
add("ru","A2","Eğitim","экзамен","sınav","isim","Экзамен был трудным.","Sınav zordu.");
add("ru","A2","Eğitim","оценка","not (okul)","isim","Я получил хорошую оценку.","İyi bir not aldım.");
add("ru","A2","Eğitim","домашнее задание","ev ödevi","isim","Я делаю домашнее задание.","Ev ödevimi yapıyorum.");
add("ru","A2","Toplum","общество","toplum","isim","Общество меняется.","Toplum değişiyor.");
add("ru","B1","İş ve Kariyer","карьера","kariyer","isim","Его карьера успешна.","Kariyeri başarılı.");
add("ru","B1","İş ve Kariyer","опыт","deneyim","isim","У него большой опыт.","Büyük bir deneyimi var.");
add("ru","B1","İş ve Kariyer","собеседование","iş görüşmesi","isim","У меня собеседование завтра.","Yarın bir iş görüşmem var.");
add("ru","B1","İş ve Kariyer","резюме","özgeçmiş","isim","Отправь мне своё резюме.","Bana özgeçmişini gönder.");
add("ru","B1","İş ve Kariyer","должность","pozisyon (iş)","isim","Он получил новую должность.","Yeni bir pozisyon aldı.");
add("ru","B1","İş ve Kariyer","повышение","terfi","isim","Он получил повышение.","Terfi aldı.");
add("ru","B1","İş ve Kariyer","увольнение","işten çıkarma","isim","Увольнение было неожиданным.","İşten çıkarılma beklenmedikti.");
add("ru","B1","İş ve Kariyer","совещание","toplantı","isim","Совещание началось вовремя.","Toplantı zamanında başladı.");
add("ru","B1","İş ve Kariyer","договор","sözleşme","isim","Подпиши договор.","Sözleşmeyi imzala.");
add("ru","B1","İş ve Kariyer","обязанность","sorumluluk","isim","Это моя обязанность.","Bu benim sorumluluğum.");
add("ru","B1","Seyahat","путешествие","seyahat (isim)","isim","Путешествие было незабываемым.","Seyahat unutulmazdı.");
add("ru","B1","Seyahat","паспорт","pasaport","isim","Мой паспорт действителен.","Pasaportum geçerli.");
add("ru","B1","Seyahat","виза","vize","isim","Мне нужна виза.","Bir vizeye ihtiyacım var.");
add("ru","B1","Seyahat","багаж","bagaj","isim","Мой багаж тяжёлый.","Bagajım ağır.");
add("ru","B1","Seyahat","отель","otel","isim","Отель удобный.","Otel rahat.");
add("ru","B1","Seyahat","бронирование","rezervasyon","isim","Я сделал бронирование.","Bir rezervasyon yaptım.");
add("ru","B1","Seyahat","аэропорт","havaalanı","isim","Аэропорт далеко.","Havaalanı uzak.");
add("ru","B1","Seyahat","маршрут","güzergah / rota","isim","Мы изменили маршрут.","Rotayı değiştirdik.");
add("ru","B1","Seyahat","достопримечательность","turistik yer","isim","Это известная достопримечательность.","Bu ünlü bir turistik yer.");
add("ru","B1","Seyahat","экскурсия","tur / gezi","isim","Экскурсия была интересной.","Tur ilginçti.");
add("ru","B1","Eğitim","образование","eğitim","isim","Образование важно.","Eğitim önemlidir.");
add("ru","B1","Eğitim","университет (2)","üniversite (2)","isim","Он учится в университете.","Üniversitede okuyor.");
add("ru","B1","Eğitim","степень","derece / unvan","isim","У него степень магистра.","Yüksek lisans derecesi var.");
add("ru","B1","Eğitim","специальность","branş / uzmanlık","isim","Моя специальность — экономика.","Branşım ekonomi.");
add("ru","B1","Eğitim","стипендия","burs","isim","Он получил стипендию.","Bir burs aldı.");
add("ru","B1","Eğitim","исследование","araştırma","isim","Это важное исследование.","Bu önemli bir araştırma.");
add("ru","B1","Eğitim","знание","bilgi","isim","Знание — это сила.","Bilgi güçtür.");
add("ru","B1","Eğitim","навык","beceri","isim","Это полезный навык.","Bu faydalı bir beceri.");
add("ru","B1","Teknoloji","технология","teknoloji","isim","Технология быстро развивается.","Teknoloji hızla gelişiyor.");
add("ru","B1","Teknoloji","данные","veri","isim","Данные важны.","Veri önemlidir.");
add("ru","B1","Teknoloji","программа","program (yazılım)","isim","Эта программа полезна.","Bu program faydalı.");
add("ru","B1","Teknoloji","система","sistem","isim","Система работает хорошо.","Sistem iyi çalışıyor.");
add("ru","B1","Teknoloji","устройство","cihaz","isim","Это новое устройство.","Bu yeni bir cihaz.");
add("ru","B1","Teknoloji","загружать","indirmek / yüklemek","fiil","Я загружаю файл.","Bir dosya indiriyorum.");
add("ru","B1","Teknoloji","подключаться","bağlanmak","fiil","Я подключаюсь к интернету.","İnternete bağlanıyorum.");
add("ru","B1","Çevre","окружающая среда","çevre","isim","Мы защищаем окружающую среду.","Çevreyi koruyoruz.");
add("ru","B1","Çevre","загрязнение","kirlilik","isim","Загрязнение воздуха растёт.","Hava kirliliği artıyor.");
add("ru","B1","Çevre","переработка","geri dönüşüm","isim","Переработка важна.","Geri dönüşüm önemlidir.");
add("ru","B1","Çevre","климат","iklim","isim","Климат меняется.","İklim değişiyor.");
add("ru","B1","Çevre","природа","doğa","isim","Природа прекрасна.","Doğa güzeldir.");
add("ru","B1","Çevre","энергия","enerji","isim","Солнечная энергия чистая.","Güneş enerjisi temizdir.");
add("ru","B1","Doğa","лес","orman","isim","Лес зелёный.","Orman yeşildir.");
add("ru","B1","Doğa","гора","dağ","isim","Гора высокая.","Dağ yüksek.");
add("ru","B1","Doğa","река","nehir","isim","Река течёт быстро.","Nehir hızlı akıyor.");
add("ru","B1","Doğa","море","deniz","isim","Море синее.","Deniz mavidir.");
add("ru","B1","Doğa","озеро","göl","isim","Озеро спокойное.","Göl sakindir.");
add("ru","B1","Bilim","наука","bilim","isim","Наука важна для общества.","Bilim toplum için önemlidir.");
add("ru","B1","Bilim","эксперимент","deney","isim","Эксперимент был успешным.","Deney başarılıydı.");
add("ru","B1","Bilim","теория","teori","isim","Это интересная теория.","Bu ilginç bir teori.");
add("ru","B1","Politika ve Hukuk","закон","kanun","isim","Закон ясен.","Kanun nettir.");
add("ru","B1","Politika ve Hukuk","правительство","hükümet","isim","Правительство приняло решение.","Hükümet karar verdi.");
add("ru","B1","Politika ve Hukuk","выборы","seçim","isim","Выборы состоятся в июне.","Seçim haziranda yapılacak.");
add("ru","B1","Politika ve Hukuk","право","hak","isim","У каждого есть право.","Herkesin bir hakkı vardır.");
add("ru","B1","Kişilik","характер","karakter (kişilik)","isim","У неё сильный характер.","Güçlü bir karakteri var.");
add("ru","B1","Kişilik","терпеливый","sabırlı","sıfat","Он очень терпеливый.","O çok sabırlı.");
add("ru","B1","Kişilik","нетерпеливый","sabırsız","sıfat","Она нетерпеливая.","O sabırsız.");
add("ru","B1","Kişilik","честный","dürüst","sıfat","Он честный человек.","O dürüst bir insan.");
add("ru","B1","Kişilik","ленивый","tembel","sıfat","Иногда он ленивый.","Bazen tembeldir.");
add("ru","B1","Kişilik","трудолюбивый","çalışkan","sıfat","Она трудолюбивая.","O çalışkandır.");
add("ru","B1","Kişilik","вежливый","kibar","sıfat","Он всегда вежливый.","Her zaman kibardır.");
add("ru","B1","Kişilik","грубый","kaba","sıfat","Это было грубо.","Bu kabaydı.");
add("ru","B1","Kişilik","щедрый","cömert","sıfat","Он щедрый.","O cömert.");
add("ru","B1","Kişilik","эгоистичный","bencil","sıfat","Иногда она эгоистична.","Bazen bencildir.");
add("ru","B1","Sanat","искусство","sanat","isim","Искусство вдохновляет.","Sanat ilham verir.");
add("ru","B1","Sanat","музыка","müzik","isim","Я люблю музыку.","Müziği severim.");
add("ru","B1","Sanat","картина","resim (tablo)","isim","Картина прекрасна.","Tablo güzeldir.");
add("ru","B1","Sanat","театр","tiyatro","isim","Мы идём в театр.","Tiyatroya gidiyoruz.");
add("ru","B1","Sanat","концерт","konser","isim","Концерт был отличным.","Konser harikaydı.");
add("ru","B1","Medya","телевидение","televizyon","isim","Я смотрю телевидение.","Televizyon izliyorum.");
add("ru","B1","Medya","газета","gazete","isim","Я читаю газету.","Gazete okuyorum.");
add("ru","B1","Medya","журнал","dergi","isim","Этот журнал интересный.","Bu dergi ilginç.");
add("ru","B1","Medya","реклама","reklam","isim","Реклама повсюду.","Reklam her yerde.");
add("ru","B1","Ekonomi","экономика","ekonomi","isim","Экономика растёт.","Ekonomi büyüyor.");
add("ru","B1","Ekonomi","рынок","piyasa / pazar","isim","Рынок нестабильный.","Piyasa istikrarsız.");
add("ru","B1","Ekonomi","инфляция","enflasyon","isim","Инфляция растёт.","Enflasyon artıyor.");
add("ru","B1","Ekonomi","прибыль","kâr","isim","Компания получила прибыль.","Şirket kâr elde etti.");
add("ru","B1","Ekonomi","инвестиция","yatırım","isim","Это хорошая инвестиция.","Bu iyi bir yatırım.");
add("ru","B1","Deyimler","По моему мнению","bence","ifade","По моему мнению, это правильно.","Bence bu doğru.");
add("ru","B1","Deyimler","Я думаю, что","bence / düşünüyorum ki","ifade","Я думаю, что он прав.","Bence o haklı.");
add("ru","B1","Deyimler","Возможно","muhtemelen","ifade","Возможно, он придёт позже.","Muhtemelen daha sonra gelecek.");
add("ru","B1","Deyimler","На самом деле","aslında","ifade","На самом деле, это не так.","Aslında bu böyle değil.");
add("ru","B1","Deyimler","С другой стороны","öte yandan","ifade","С другой стороны, он тоже прав.","Öte yandan o da haklı.");
add("ru","B1","Deyimler","Кстати","bu arada","ifade","Кстати, ты читал эту книгу?","Bu arada, bu kitabı okudun mu?");
add("ru","B1","Deyimler","Другими словами","başka bir deyişle","ifade","Другими словами, он лжёт.","Başka bir deyişle, yalan söylüyor.");
add("ru","B1","Deyimler","Например","örneğin","ifade","Например, мы могли бы заказать пиццу.","Örneğin pizza sipariş edebiliriz.");
add("ru","B1","Deyimler","Без сомнения","şüphesiz","ifade","Без сомнения, он лучший.","Şüphesiz o en iyisi.");
add("ru","B1","Deyimler","Короче говоря","kısaca","ifade","Короче говоря, это не работает.","Kısaca, işe yaramıyor.");
add("ru","B1","İletişim","обсуждать","tartışmak (konuşmak)","fiil","Мы обсуждаем план.","Planı tartışıyoruz.");
add("ru","B1","İletişim","предлагать","önermek","fiil","Я предлагаю встречу.","Bir buluşma öneriyorum.");
add("ru","B1","İletişim","соглашаться","katılmak (fikre)","fiil","Я согласен с тобой.","Seninle aynı fikirdeyim.");
add("ru","B1","İletişim","спорить","tartışmak (kavga)","fiil","Они спорят о деньгах.","Para hakkında tartışıyorlar.");
add("ru","B1","İletişim","убеждать","ikna etmek","fiil","Я убедил его.","Onu ikna ettim.");
add("ru","B1","Toplum","традиция","gelenek","isim","Это старая традиция.","Bu eski bir gelenek.");
add("ru","B1","Toplum","культура","kültür","isim","Каждая культура особенная.","Her kültür özeldir.");
add("ru","B1","Toplum","поколение","nesil","isim","Новое поколение думает иначе.","Yeni nesil farklı düşünüyor.");
add("ru","B1","Toplum","равенство","eşitlik","isim","Равенство важно.","Eşitlik önemlidir.");
add("ru","B1","Toplum","свобода","özgürlük","isim","Свобода — это право.","Özgürlük bir haktır.");
add("ru","B2","Soyut Kavramlar","подход","yaklaşım","isim","Это новый подход.","Bu yeni bir yaklaşım.");
add("ru","B2","Soyut Kavramlar","фактор","faktör","isim","Это важный фактор.","Bu önemli bir faktör.");
add("ru","B2","Soyut Kavramlar","проблема","sorun / mesele","isim","Это сложная проблема.","Bu karmaşık bir sorun.");
add("ru","B2","Soyut Kavramlar","тенденция","eğilim","isim","Это растущая тенденция.","Bu artan bir eğilim.");
add("ru","B2","Soyut Kavramlar","возможность","olanak / fırsat","isim","Это хорошая возможность.","Bu iyi bir fırsat.");
add("ru","B2","Soyut Kavramlar","последствие","sonuç (etki)","isim","Это имеет серьёзные последствия.","Bunun ciddi sonuçları var.");
add("ru","B2","Soyut Kavramlar","противоречие","çelişki","isim","Здесь есть противоречие.","Burada bir çelişki var.");
add("ru","B2","Soyut Kavramlar","предположение","varsayım","isim","Это всего лишь предположение.","Bu sadece bir varsayım.");
add("ru","B2","Görüşler","с точки зрения","açısından","ifade","С точки зрения экономики, это разумно.","Ekonomik açıdan, bu mantıklı.");
add("ru","B2","Görüşler","в некоторой степени","bir ölçüde","ifade","Это верно в некоторой степени.","Bu bir ölçüde doğru.");
add("ru","B2","Görüşler","несомненно","şüphesiz (2)","ifade","Несомненно, это правда.","Şüphesiz bu doğru.");
add("ru","B2","Görüşler","стоит отметить, что","şunu belirtmek gerekir ki","ifade","Стоит отметить, что результаты различаются.","Şunu belirtmek gerekir ki sonuçlar değişir.");
add("ru","B2","Görüşler","с одной стороны","bir yandan","ifade","С одной стороны, это полезно.","Bir yandan, bu faydalı.");
add("ru","B2","Eylemler","воспринимать","algılamak","fiil","Он воспринимает это иначе.","Bunu farklı algılıyor.");
add("ru","B2","Eylemler","достигать","ulaşmak / başarmak","fiil","Он достиг своей цели.","Hedefine ulaştı.");
add("ru","B2","Eylemler","недооценивать","hafife almak","fiil","Не недооценивай его.","Onu hafife alma.");
add("ru","B2","Eylemler","подчёркивать","vurgulamak","fiil","Он подчёркивает важность этого.","Bunun önemini vurguluyor.");
add("ru","B2","Eylemler","сомневаться","şüphe duymak","fiil","Я сомневаюсь в этом.","Bundan şüphe duyuyorum.");
add("ru","B2","Sıfatlar","значительный","önemli ölçüde","sıfat","Значительное улучшение.","Önemli ölçüde bir iyileşme.");
add("ru","B2","Sıfatlar","решающий","belirleyici / kritik","sıfat","Это решающее решение.","Bu kritik bir karar.");
add("ru","B2","Sıfatlar","действительный","geçerli","sıfat","Этот договор действителен.","Bu sözleşme geçerli.");
add("ru","B2","Sıfatlar","очевидный","aşikar / bariz","sıfat","Это очевидная ошибка.","Bu bariz bir hata.");
add("ru","B2","Sıfatlar","сложный","karmaşık","sıfat","Это сложная система.","Bu karmaşık bir sistem.");
add("ru","B2","Sıfatlar","эффективный","verimli / etkili","sıfat","Это эффективный метод.","Bu verimli bir yöntem.");
add("ru","B2","İş ve Kariyer","предприниматель","girişimci","isim","Он успешный предприниматель.","O başarılı bir girişimci.");
add("ru","B2","İş ve Kariyer","стратегия","strateji","isim","Это хорошая стратегия.","Bu iyi bir strateji.");
add("ru","B2","İş ve Kariyer","конкуренция","rekabet","isim","Конкуренция высокая.","Rekabet yüksek.");
add("ru","B2","İş ve Kariyer","сотрудничество","işbirliği","isim","Сотрудничество важно.","İşbirliği önemlidir.");
add("ru","B2","İş ve Kariyer","ответственность","sorumluluk (2)","isim","Это большая ответственность.","Bu büyük bir sorumluluk.");
add("ru","B2","Sağlık","диагноз","teşhis","isim","Врач поставил диагноз.","Doktor teşhis koydu.");
add("ru","B2","Sağlık","лечение","tedavi","isim","Лечение эффективно.","Tedavi etkilidir.");
add("ru","B2","Sağlık","симптом","belirti","isim","Это распространённый симптом.","Bu yaygın bir belirti.");
add("ru","B2","Sağlık","хронический","kronik","sıfat","Это хроническое заболевание.","Bu kronik bir hastalık.");
add("ru","B2","Sağlık","иммунитет","bağışıklık","isim","Иммунитет ослаблен.","Bağışıklık zayıflamış.");
add("ru","B2","Çevre","устойчивое развитие","sürdürülebilir kalkınma","isim","Устойчивое развитие важно.","Sürdürülebilir kalkınma önemlidir.");
add("ru","B2","Çevre","возобновляемая энергия","yenilenebilir enerji","isim","Возобновляемая энергия — будущее.","Yenilenebilir enerji gelecektir.");
add("ru","B2","Çevre","биоразнообразие","biyoçeşitlilik","isim","Биоразнообразие сокращается.","Biyoçeşitlilik azalıyor.");
add("ru","B2","Çevre","вымирание","neslin tükenmesi","isim","Вымирание видов ускоряется.","Türlerin neslinin tükenmesi hızlanıyor.");
add("ru","B2","Teknoloji","искусственный интеллект","yapay zeka","isim","Искусственный интеллект развивается быстро.","Yapay zeka hızla gelişiyor.");
add("ru","B2","Teknoloji","алгоритм","algoritma","isim","Это сложный алгоритм.","Bu karmaşık bir algoritma.");
add("ru","B2","Teknoloji","безопасность (кибер)","güvenlik (siber)","isim","Кибербезопасность важна.","Siber güvenlik önemlidir.");
add("ru","B2","Politika ve Hukuk","конституция","anayasa","isim","Конституция защищает права.","Anayasa hakları korur.");
add("ru","B2","Politika ve Hukuk","суд","mahkeme","isim","Суд принял решение.","Mahkeme karar verdi.");
add("ru","B2","Politika ve Hukuk","дипломатия","diplomasi","isim","Дипломатия важна.","Diplomasi önemlidir.");
add("ru","B2","Deyimler","Как говорится","dendiği gibi","ifade","Как говорится, время лечит.","Dendiği gibi, zaman iyileştirir.");
add("ru","B2","Deyimler","В конце концов","sonunda / nihayetinde","ifade","В конце концов, всё получилось.","Sonunda her şey yolunda gitti.");
add("ru","B2","Deyimler","Что касается меня","bana gelince","ifade","Что касается меня, я согласен.","Bana gelince, katılıyorum.");
add("ru","B2","Deyimler","Судя по всему","görünüşe göre","ifade","Судя по всему, он опоздает.","Görünüşe göre geç kalacak.");
add("ru","B2","Deyimler","В любом случае","her halükarda","ifade","В любом случае, спасибо.","Her halükarda, teşekkürler.");
add("ru","B2","Deyimler","Тем не менее","yine de / buna rağmen","ifade","Тем не менее, он попытался.","Yine de denedi.");
add("ru","B2","Deyimler","Более того","dahası","ifade","Более того, это неправда.","Dahası, bu doğru değil.");
add("ru","B2","Deyimler","В целом","genel olarak","ifade","В целом, всё хорошо.","Genel olarak her şey iyi.");
add("ru","B2","Bağlaçlar","хотя","gerçi / -e rağmen","bağlaç","Хотя было холодно, мы вышли.","Soğuk olmasına rağmen dışarı çıktık.");
add("ru","B2","Bağlaçlar","несмотря на","-e rağmen","edat","Несмотря на дождь, мы пошли гулять.","Yağmura rağmen yürüyüşe çıktık.");
add("ru","B2","Bağlaçlar","в то время как","-iken","bağlaç","В то время как я готовил, она убиралась.","Ben yemek yaparken o temizlik yapıyordu.");
add("ru","B2","Bağlaçlar","если только не","-medikçe","bağlaç","Я не пойду, если только ты не позвонишь.","Aramadıkça gitmeyeceğim.");
add("ru","B2","Soyut Kavramlar","парадокс","paradoks","isim","Это интересный парадокс.","Bu ilginç bir paradoks.");
add("ru","B2","Soyut Kavramlar","дилемма","ikilem","isim","Он столкнулся с дилеммой.","Bir ikilemle karşılaştı.");
add("ru","B2","Soyut Kavramlar","гипотеза","hipotez / varsayım","isim","Это всего лишь гипотеза.","Bu sadece bir hipotez.");
add("ru","B2","Sıfatlar","противоречивый","tartışmalı","sıfat","Это противоречивая тема.","Bu tartışmalı bir konu.");
add("ru","B2","Sıfatlar","объективный","tarafsız / nesnel","sıfat","Отчёт был объективным.","Rapor nesneldi.");
add("ru","B2","Sıfatlar","субъективный","öznel","sıfat","Это субъективное мнение.","Bu öznel bir görüş.");
add("ru","B2","Eğitim","критическое мышление","eleştirel düşünme","isim","Критическое мышление важно.","Eleştirel düşünme önemlidir.");
add("ru","B2","Eğitim","академический","akademik","sıfat","Это академическая работа.","Bu akademik bir çalışma.");
